drugs:
    path: "./imported_data/tbl_drugs.parquet"

clinical_trials:
    path: "./imported_data/tbl_clinical_trials.parquet"

pubmeds:
    path: "./imported_data/tbl_pubmed.parquet"

output:
    path: "./processed_data/graph.json"